server:
  port: 8762
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://adrien:123123@$lcalhost:8760/eureka/
  instance:
    hostname: localhost