server:
  port: 9776
eureka:
  client:
    service-url:
      defaultZone: http://adrien:123123@localhost:9765/eureka/
spring:
  application:
    name: eureka-producer
  zipkin:
    base-url: http://localhost:18090
  sleuth:
    sampler:
      percentage: 1.0




