server:
  port: 10080
spring:
  application:
    name: eureka-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AdrienLaw/BorgesPhotoStudio/
          search-paths: config-repo
          username: adrienlaw@126.com
          password: up842514938
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  basic:
    enabled: false
  user:
    name: adrien
    password: 123123
eureka:
  client:
    service-url:
      defaultZone: http://adrien:123123@localhost:9765/eureka

management:
  security:
    enabled: false
