server:
  port: 8080

# 组合使用
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_foo_path_headers_to_httpbin
#          uri: http://ityouknow.com
#          predicates:
#            - Host=**.foo.org
#            - Path=/headers
#            - Method=GET
#            - Header=X-Request-Id, \d+
#            - Query=foo, ba.
#            - Query=baz
#            - Cookie=chocolate, ch.p
#            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]


# 通过请求 ip 地址进行匹配
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: remoteaddr_route
#          uri: http://ityouknow.com
#          predicates:
#            - RemoteAddr=192.168.1.10/24


# 根据请求参数匹配
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://ityouknow.com
#          predicates:
#            - Query=smile
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://ityouknow.com
#          predicates:
#            - Query=keep, pu.

# 通过请求路径匹配
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#          uri: http://ityouknow.com
#          predicates:
#            - Path=/foo/{segment}


# 请求方式
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: method_route
#          uri: http://ityouknow.com
#          predicates:
#            - Method=GET

# host
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#          uri: http://ityouknow.com
#          predicates:
#            - Host=**.ityouknow.com



# Header
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: header_route
#          uri: http://ityouknow.com
#          predicates:
#            - Header=X-Request-Id, \d+


# Cookie
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: cookie_route
#          uri: http://ityouknow.com
#          predicates:
#            - Cookie=ityouknow, kee.e


# Before Route Predicate
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: after_route
#          uri: http://ityouknow.com
#          predicates:
#           - Before=2020-01-09T16:06:06+08:00[Asia/Shanghai]
#


#Between Route Predicate
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: after_route
#          uri: http://ityouknow.com
#          predicates:
#           - Between=2018-01-20T06:06:06+08:00[Asia/Shanghai], 2019-01-20T06:06:06+08:00[Asia/Shanghai]

# Predicate
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: time_route
#          uri: http://ityouknow.com
#          predicates:
#           - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]

#001
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: neo_route
#          uri: http://www.ityouknow.com
#          predicates:
#            - Path=/spring-cloud

