server:
  port: 9765
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enableSelfPreservation: false
  instance:
    hostname: 127.0.0.1
spring:
  application:
    name: eureka
security:
  basic:
    enabled: false
  user:
    name: adrien
    password: 123123


